cld/urls.py
from django.urls import path
from . import views


app_name = 'cld'
urlpatterns = [
    path('', views.calendar, name="calendar"),
]

introduction/urls.py
from django.urls import path
from . import views

app_name = 'introduction'
urlpatterns = [
    path('', views.profile, name="profile"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('introduction/', include('introduction.urls')),
    path('', views.main, name="main"),
    path('posts/', include('posts.urls')),
    path('calendar/', include('cld.urls')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import new, create, main, show, update, delete

app_name = "posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('/show/<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delte/<int:id>/', delete, name = "delete"),
]

cld/models.py
from django.db import models

# Create your models here.

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
 
# Create your models here.
 
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()    
    view_count = models.IntegerField(default = 0)    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to = 'images/',null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)


class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

cld/views.py
from django.shortcuts import render

# Create your views here.
def calendar(request):
    return render(request, 'cld/calendar.html')

introduction/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'introduction/profile.html')

myblog/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post


def new(request):
    return render(request, 'posts/new.html')


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        Post.objects.create(title=title,user=user,content=content,image=image)
        return redirect('posts:main')

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts': posts})


def show(request, id):
    post = Post.objects.get(pk=id)
    post.view_count += 1
    post.save()
    return render(request, 'posts/show.html', {'post': post})


def update(request,id):
    post = get_object_or_404(Post,pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image') 
        post.save()
        return redirect('posts:show',post.id)
    return render(request, 'posts/update.html',{"post":post})


def delete(request,id):
    post = get_object_or_404(Post,pk=id)
    post.delete()
    return redirect("posts:main")

cld/templates/cld/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="month">
        <ul>
        <li>July<br><span style="font-size:18px">2020</span></li>
        </ul>
    </div>
    
    <ul class="weekdays">
        <li>Mo</li>
        <li>Tu</li>
        <li>We</li>
        <li>Th</li>
        <li>Fr</li>
        <li>Sa</li>
        <li>Su</li>
    </ul>
    
    <ul class="days">
        <li></li>
        <li></li>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
        <li>10</li>
        <li>11</li>
        <li>12</li>
        <li>13</li>
        <li>14</li>
        <li><span class="active">15(멋사 정기 세션)</span></li>
        <li>16</li>
        <li><span class="active">17(일화실 중간 고사)</span></li>
        <li>18</li>
        <li>19</li>
        <li>20</li>
        <li>21</li>
        <li><span class="active">22(멋사 정기 세션)</span></li>
        <li>23</li>
        <li>24</li>
        <li>25</li>
        <li>26</li>
        <li>27</li>
        <li><span class="active">28(일화실 기말 고사)</span></li>
        <li><span class="active">29(멋사 정기 세션)</span></li>
        <li><span class="active">30(대전)</li>
        <li>31</li>
    </ul>
{% endblock %}

introduction/templates/introduction/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 style = "color: rgb(33, 82, 88); text-align: center; font-weight: bold;">간단한 자기소개</h1>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://ppss.kr/wp-content/uploads/2017/05/%ED%8F%89%EC%B0%BD%EB%8F%99%EA%B3%84%EC%98%AC%EB%A6%BC%ED%94%BD%EA%B0%9C%EC%B5%9C-1.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <p style = "color: red; font-weight: bold; font-size: 50px">시골 사람</p>
        <p style = "color: red; font-weight: bold; font-size: 20px">평창 출생</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://data.ac-illust.com/data/thumbnails/ab/ab1e242e7fbd869b1f73695533c018eb_t.jpeg" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <p style = "color: red; font-weight: bold; font-size: 50px">대가족</p>
        <p style = "color: red; font-weight: bold; font-size: 20px">4남매</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/dgdg.jpg' %}" alt="Third slide">
    <div class="carousel-caption d-none d-md-block">
        <p style = "color: red; font-weight: bold; font-size: 50px">학과</p>
        <p style = "color: red; font-weight: bold; font-size: 20px">기계로봇에너지공학과</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

myblog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title></title>
  </head>
  <body>
    
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class= "kmg">
<p class="hi"><strong>좋은 저녁입니다! 멋-!하-!</strong></p>
<div class = "container" >
  <div class="cardd">
      <img src="{% static 'images/ps1.jpg' %}" class="card-img-top" alt="고" style="height: 18rem;">
      <div class="card-body">
        <h5 class="card-title">안녕하세요</h5>
        <p class="card-text"><strong>뭘 만들어야 할지</strong></p>
      </div>
    </div>
    <div class="cardd">
      <img src="{% static 'images/ps2.jpg' %}" class="card-img-top" alt="명" style="height: 18rem;">
      <div class="card-body">
        <h5 class="card-title">제 페이지에</h5>
        <p class="card-text"><strong>끝내 정하지 못해서</strong></p>
      </div>
    </div>
    <div class="cardd">
      <img src="{% static 'images/ps3.jpg' %}" class="card-img-top" alt="기" style="height: 18rem;">
      <div class="card-body">
        <h5 class="card-title">와주셔서</h5>
        <p class="card-text"><strong>그냥 제가 유용하게 쓸 수 있는</strong></p>
      </div>
    </div>
    <div class="cardd">
      <img src="{% static 'images/ps4.jpg' %}" class="card-img-top" alt="핳" style="height: 18rem;">
      <div class="card-body">
        <h5 class="card-title">감사합니다</h5>
        <p class="card-text"><strong>사이트를 만들었습니다.</strong></p>
      </div>
    </div>
</div>
</div>

{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href='{% url "main" %}'>고명기</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href='{% url "main" %}'>home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href='{% url "introduction:profile" %}'>introduction</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.op.gg/summoner/userName=%EB%B6%95%EC%96%B4%EC%97%91%EA%B8%B0%EC%8A%A4"  target="_blank">롤</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.youtube.com/" target="_blank">유튜브</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://eclass.dongguk.edu/index.jsp">이클래스</a>
      </li>
      </li>
      <li class="nav-item">
        <a class="nav-link" href='{% url "cld:calendar" %}'>스케줄표</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href='{% url "posts:main" %}'>메세지
        </a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right ">
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
        <div class="dropdown-menu">
          {% if user.is_authenticated %} {# 유저가 로그인 중이면 #}
            <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">Logout</a>
            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change PW</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">Login</a>
            <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
          {% endif %}
        </div>
      </li>
    </ul>
  </div>
</nav>

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %} {#유저가 로그인한 상태라면 #}

        <div class="container2">
            <h1 style = "font-weight: bold; color: rgb(32, 84, 179);">메세지 보내기</h1>
            <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
            <label>글제목</label>
            <input type="text" class="form-control" name="title">
            </div>
            <div class="form-group">
            <label>메세지</label>
            <textarea class="form-control" name="content"></textarea>
            </div>
            <input type="submit" value="글 작성" class="btn btn-outline-primary">
            <input type="file" name ="image">
            </form>
        </div>
        <div class="container1">
            <br><br><br><br>
            <h1 style = "font-weight: bold; color: rgb(32, 84, 179);">메세지 함</h1>
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4 col-12">
                        <div class="card text-center" style="width: 18rem; margin-top: 20px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content }}</p>
                                {% if post.image %}
                                    <br>
                                    <img src ="{{ post.image.url }}" style="height: 60px; width:50px;">
                                {%  endif %}
                                <p>{{ post.created_at }}</p>
                                <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">자세히</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <h3> 로그인 후 이용이 가능합니다.</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container2">
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    <label>이름</label>
    <input type="text" class="form-control" name="title">
    </div>
    <div class="form-group">
    <label>메세지</label>
    <textarea class="form-control" name="content"></textarea>
    </div>
    <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<br><br><br><br>
<h2 style = "color: powderblue; font-weight: bold; text-align: center;">상세보기 페이지</h2>
<br><br><br><br>
<h5 style = "font-weight: bold;">글 제목 : {{ post.title }} </h5><br>
{% if post.user %}
    <h5 style = "font-weight: bold;">이름 : {{ post.user }} </h5><br>
{% else %}
    <h5 style = "font-weight: bold;">이름: 알 수 없음 </h5><br>
{% endif %}
<h5 style = "font-weight: bold;">메세지 : {{ post.content }} </h5><br>
<h5 style = "font-weight: bold;">작성 시각 : {{ post.created_at }} </h5><br>
<h5 style = "font-weight: bold;">조회수: {{ post.view_count }}</h5>
<div class = "kmg123123" style = "text-align: center;">
    {% if user == post.user %}
        <a href = "{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
        <a href = "{% url 'posts:delete' post.pk %}" class="btn btn-danger">삭제하기</a>
    {% endif %}
</div>
    {% if post.image %}
        <br>
        <img src ="{{ post.image.url }}" style="height: 50%; width:50%; margin-left:auto; margin-right:auto; display: block;">
    {%  endif %}

{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>
        새로운 글 작성하기
    </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    <label>글 제목</label>
    <input type="text" class="form-control" name="title" value= "{{post.title}}">
    </div>
    <div class="form-group">
    <label>글 내용</label>
    <textarea class="form-control" name="content">{{post.content}}</textarea>
    </div>
    <input type="submit" value="글 수정" class="btn btn-outline-primary">
    <input type="file" name ="image">
    </form>
</div>
{% endblock %}